#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.caching=true
org.gradle.configuration-cache=true
#Kotlin
kotlin.code.style=official
kotlin.js.compiler=ir
#Due to e: Failed to build cache for /Users/eyedol/.gradle/caches/modules-2/files-2.1/org.jetbrains.compose.foundation/foundation-uikitsimarm64/1.7.3/2b48244b10b743913aedf9abd915ceedafa56435/foundation.
#As a workaround, please try to disable compiler caches (kotlin.native.cacheKind=none)
kotlin.native.cacheKind=none
#MPP
kotlin.mpp.enableCInteropCommonization=true
#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
kanalytics.sampleDebug=debug
