// Copyright 2024, Addhen Ltd and the kanalytics project contributors
// SPDX-License-Identifier: Apache-2.0

package com.addhen.kanalytics.viewer.app.shared.ui.theme
import androidx.compose.ui.graphics.Color

// Light theme
internal val primaryLight = Color(0xFF07677F)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFB7EAFF)
internal val onPrimaryContainerLight = Color(0xFF001F28)
internal val secondaryLight = Color(0xFF4C626B)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFCFE6F1)
internal val onSecondaryContainerLight = Color(0xFF071E26)
internal val tertiaryLight = Color(0xFF5A5B7E)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFE1E0FF)
internal val onTertiaryContainerLight = Color(0xFF171837)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF410002)
internal val backgroundLight = Color(0xFFF5FAFD)
internal val onBackgroundLight = Color(0xFF171C1F)
internal val surfaceLight = Color(0xFFF5FAFD)
internal val onSurfaceLight = Color(0xFF171C1F)
internal val surfaceVariantLight = Color(0xFFDBE4E8)
internal val onSurfaceVariantLight = Color(0xFF40484C)
internal val outlineLight = Color(0xFF70787C)
internal val outlineVariantLight = Color(0xFFBFC8CC)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF2C3134)
internal val inverseOnSurfaceLight = Color(0xFFEDF1F4)
internal val inversePrimaryLight = Color(0xFF88D1EC)
internal val surfaceDimLight = Color(0xFFD6DBDE)
internal val surfaceBrightLight = Color(0xFFF5FAFD)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFEFF4F7)
internal val surfaceContainerLight = Color(0xFFEAEFF2)
internal val surfaceContainerHighLight = Color(0xFFE4E9EC)
internal val surfaceContainerHighestLight = Color(0xFFDEE3E6)

// Dark theme
internal val primaryDark = Color(0xFF82D3E0)
internal val onPrimaryDark = Color(0xFF003915)
internal val primaryContainerDark = Color(0xFF38F377)
internal val onPrimaryContainerDark = Color(0xFF004A1D)
internal val secondaryDark = Color(0xFF88D893)
internal val onSecondaryDark = Color(0xFF003915)
internal val secondaryContainerDark = Color(0xFF005221)
internal val onSecondaryContainerDark = Color(0xFFA0F1AA)
internal val tertiaryDark = Color(0xFFFFCCED)
internal val onTertiaryDark = Color(0xFF5E0052)
internal val tertiaryContainerDark = Color(0xFFF98CDD)
internal val onTertiaryContainerDark = Color(0xFF4C0042)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF0D150D)
internal val onBackgroundDark = Color(0xFFDBE5D8)
internal val surfaceDark = Color(0xFF121414)
internal val onSurfaceDark = Color(0xFFE3E2E2)
internal val surfaceVariantDark = Color(0xFF414849)
internal val onSurfaceVariantDark = Color(0xFFC1C8C9)
internal val outlineDark = Color(0xFF8B9293)
internal val outlineVariantDark = Color(0xFF414849)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFE3E2E2)
internal val inverseOnSurfaceDark = Color(0xFF2F3131)
internal val inversePrimaryDark = Color(0xFF006E2E)
internal val surfaceDimDark = Color(0xFF121414)
internal val surfaceBrightDark = Color(0xFF383939)
internal val surfaceContainerLowestDark = Color(0xFF0D0E0F)
internal val surfaceContainerLowDark = Color(0xFF1A1C1C)
internal val surfaceContainerDark = Color(0xFF1F2020)
internal val surfaceContainerHighDark = Color(0xFF292A2A)
internal val surfaceContainerHighestDark = Color(0xFF343535)

internal val eventPropertiesDark = Color(0xFF7AE43A)
internal val eventNameDark = Color(0xFF0F73DF)
internal val eventHeaderDark = Color(0xFFE40B64)
internal val eventNameLight = Color(0xFF004AB0)
internal val eventHeaderLight = Color(0xFF870F94)
internal val eventPropertiesLight = Color(0xFF334D00)

internal val searchHighlightLight = Color(0xFFFCD47D)
internal val searchHighlightDark = Color(0xFFE4E4E4)
