// Copyright 2024, Addhen Ltd and the kanalytics project contributors
// SPDX-License-Identifier: Apache-2.0

package com.addhen.kanalytics.viewer

import com.addhen.kanalytics.KAnalyticsEvent
import com.addhen.kanalytics.KTrackerName
import com.addhen.kanalytics.viewer.app.NotificationManager
import com.addhen.kanalytics.viewer.app.shared.AppCoroutineDispatchers
import com.addhen.kanalytics.viewer.app.shared.data.model.EventData
import com.addhen.kanalytics.viewer.app.shared.data.repository.EventDataRepository
import com.addhen.kanalytics.viewer.app.shared.data.repository.EventRepository
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.MainScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlinx.datetime.Instant

public class KAnalyticsCollector(
  showShortcut: Boolean = true,
  duration: RetentionPolicyManager.DayDuration = RetentionPolicyManager.DayDuration(7),
  shortcutManager: ShortcutManager = DefaultShortcutManager(),
  private val showNotification: Boolean = true,
  private val scope: CoroutineScope = MainScope(),
  private val repository: EventRepository = EventDataRepository.Instance,
  private val appCoroutineDispatchers: AppCoroutineDispatchers = AppCoroutineDispatchers(),
  private val notificationManager: NotificationManager = NotificationManager(),
) {

  private val retentionPolicyManager: RetentionPolicyManager = RetentionPolicyManager(
    dayDuration = duration,
    repository = repository,
  )

  init {
    shortcutManager.setupShortcut(showShortcut)
  }

  public fun onEventSent(
    kAnalyticsEvent: KAnalyticsEvent,
    kTrackerName: KTrackerName,
    onSentDate: Instant,
  ) {
    scope.launch {
      withContext(appCoroutineDispatchers.io) {
        repository.insert(
          eventData = EventData(
            id = null, // It will be auto generated by the database
            name = kAnalyticsEvent.eventName,
            trackerName = kTrackerName.value,
            description = kAnalyticsEvent.eventDescription,
            createdAt = onSentDate,
            properties = kAnalyticsEvent.properties.mapValues { it.value ?: "" },
          ),
        )
      }

      if (showNotification) {
        notificationManager.showNotification(
          eventName = kAnalyticsEvent.eventName,
          trackerName = kTrackerName.value,
        )
      }

      withContext(appCoroutineDispatchers.io) {
        retentionPolicyManager.processDataRetention()
      }
    }
  }
}
