name: Deploy to central

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/gradle.yml
  deploy:
    needs: build
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Gradle publish
        env:
          OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          OSSRH_GPG_SECRET_KEY_ID: ${{ secrets.OSSRH_GPG_SECRET_KEY_ID }}
          OSSRH_GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: >
          ./gradlew --no-configuration-cache
          publishToSonatype
          closeAndReleaseSonatypeStagingRepository
          -Psigning.gnupg.keyName='${{secrets.OSSRH_GPG_SECRET_KEY_ID}}'

      - name: Extract release notes
        id: release_notes
        uses: ffurrer2/extract-release-notes@v2

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
