name: Publish docs

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy_docs:
    runs-on: macos-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: |
          brew install cairo freetype libffi libjpeg libpng zlib
          python3 -m pip install --upgrade pip
          python3 -m pip install mike mkdocs mkdocs-material mkdocs-video "mkdocs-material[imaging]"

      - name: Copy files for the documentation site
        run: |
          cp CHANGELOG.md docs/changelog.md
          cp CONTRIBUTING.md docs/contributing.md
          cp CODE_OF_CONDUCT.md docs/code-of-conduct.md

      - name: Build site
        run: mkdocs build
        env:
          DYLD_FALLBACK_LIBRARY_PATH: /opt/homebrew/lib

      - run: |
          ./gradlew --no-configuration-cache --stacktrace :dokka:dokkaGeneratePublicationHtml

      - name: Copy Dokka output to site
        run: cp -r dokka/build/dokka/html/ docs/api/

      - name: Configure git for mike
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch origin gh-pages --depth=1

      - name: Deploy dev docs with mike
        if: ${{ success() && contains(env.VERSION_NAME, '-SNAPSHOT') }}
        env:
          KANALYTICS_VERSION: snapshot
          DYLD_FALLBACK_LIBRARY_PATH: /opt/homebrew/lib
        run: mike deploy -u --push snapshot

      - name: Deploy release docs with mike
        if: ${{ success() && !contains(env.VERSION_NAME, '-SNAPSHOT') }}
        env:
          KANALYTICS_VERSION: ${{ env.VERSION_NAME }}
          DYLD_FALLBACK_LIBRARY_PATH: /opt/homebrew/lib
        run: mike deploy -u --push ${{ env.VERSION_NAME }} latest

      - name: Delete old doc versions
        run: |
          git fetch origin gh-pages --depth=1
          scripts/delete_old_version_docs.sh
